services:

  pgdatabase:
    image: postgres:17
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5433:5432"
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ny_taxi"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ny_taxi_postgres_data: