SELECT trip_id,
vendor_name,
tpep_pickup_datetime,
tpep_dropoff_datetime,
trip_duration,
EXTRACT(HOUR FROM tpep_pickup_datetime) AS pickup_hour,
EXTRACT(DOW FROM tpep_pickup_datetime) AS pickup_day_number,
TO_CHAR(tpep_pickup_datetime,'Day') AS pickup_day_name,
EXTRACT(MONTH FROM tpep_pickup_datetime) AS pickup_month,
passenger_count,
trip_distance,
ratecode_desc,
store_and_fwd_flag,
partida,pu_borough,
llegada,do_borough,
payment_desc,
fare_amount,
extra,mta_tax,
tip_amount,
tolls_amount,
improvement_surcharge,
congestion_surcharge,
airport_fee,
total_amount
FROM {{ ref('int_trips_descrips_calc_filtros')}}
