version: 2

sources:
  - name: fuente_principal
    database: ny_taxi
    schema: public
    description: tablas en 3FN que tienen como fuente la data de taxis de nyc
    tables:
      - name: dim_vendor
        description: raw data de tabla proveedores
        columns:
          - name: vendor_id
            tests:
              - unique
              - not_null
              - accepted_values:
                  arguments:
                    values: [0,1,2]
          - name: vendor_name
            tests:
              - not_null
      - name: dim_ratecode
        description: raw data de tabla tarifas
        columns:
          - name: ratecode_id
            description: clave primaria de tabla tarifas
            tests:
              - unique
              - not_null
              - accepted_values:
                  arguments:
                    values: [1,2,3,4,5,6,99]
          - name: ratecode_desc
            tests:
              - not_null
      - name: fact_trip
        columns:
          - name: trip_id
            tests:
              - unique
              - not_null
          - name: vendor_id
            tests:
              - not_null
          - name: ratecode_id
            tests:
              - not_null
          - name: payment_type
            tests:
              - not_null
          - name: pu_location_id
            tests:
              - not_null
          - name: do_location_id
            tests:
              - not_null

      - name: dim_payment_type
        columns:
          - name: payment_type_id
            tests:
              - unique
              - not_null
              - accepted_values:
                  arguments:
                    values: [1,2,3,4,5,6,0]
          - name: payment_desc
            tests:
              - not_null
      - name: dim_location
        columns:
          - name: location_id
            tests:
              - unique
              - not_null